
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 19 08:14:55 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 49;
  public static final int CONST = 3;
  public static final int EQUALS = 32;
  public static final int MUL_EQUAL = 20;
  public static final int SEMI = 44;
  public static final int LPAREN = 42;
  public static final int GREATER = 36;
  public static final int CONTINUE = 14;
  public static final int LESS = 34;
  public static final int FOR = 12;
  public static final int MINUS = 24;
  public static final int RPAREN = 43;
  public static final int STATIC = 9;
  public static final int AND = 30;
  public static final int OR = 31;
  public static final int BOOL = 50;
  public static final int COMMA = 45;
  public static final int CLASS = 4;
  public static final int INC = 25;
  public static final int DIV = 28;
  public static final int PLUS_EQUAL = 18;
  public static final int MINUS_EQUAL = 19;
  public static final int DIV_EQUAL = 21;
  public static final int PLUS = 23;
  public static final int GREATER_EQUALS = 37;
  public static final int IF = 10;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int EQUAL = 17;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int NUMBER = 48;
  public static final int MOD = 29;
  public static final int IDENT = 47;
  public static final int BREAK = 13;
  public static final int VOID = 7;
  public static final int LBRACK = 40;
  public static final int MOD_EQUAL = 22;
  public static final int LBRACE = 38;
  public static final int ELSE = 11;
  public static final int LESS_EQUALS = 35;
  public static final int RBRACK = 41;
  public static final int READ = 16;
  public static final int NOT_EQUALS = 33;
  public static final int RBRACE = 39;
  public static final int EXTENDS = 5;
  public static final int PROG = 2;
  public static final int DEC = 26;
  public static final int PRINT = 15;
}

